src/java/model/Cart.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author Nam
 */
public class Cart {
    private int CartID;
    private int UserID;
    private int ItemID;
    private int Quantity;
    private int AvailableQuantity;
    private float Price;
    private String ItemImageURL;
    private int ItemRating;
    private String FullDescription;

    /**
     * @return the CartID
     */
    public int getCartID() {
        return CartID;
    }

    /**
     * @param CartID the CartID to set
     */
    public void setCartID(int CartID) {
        this.CartID = CartID;
    }

    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the ItemID
     */
    public int getItemID() {
        return ItemID;
    }

    /**
     * @param ItemID the ItemID to set
     */
    public void setItemID(int ItemID) {
        this.ItemID = ItemID;
    }

    /**
     * @return the Quantity
     */
    public int getQuantity() {
        return Quantity;
    }

    /**
     * @param Quantity the Quantity to set
     */
    public void setQuantity(int Quantity) {
        this.Quantity = Quantity;
    }

    /**
     * @return the Price
     */
    public float getPrice() {
        return Price;
    }

    /**
     * @param Price the Price to set
     */
    public void setPrice(float Price) {
        this.Price = Price;
    }

    /**
     * @return the ItemImageURL
     */
    public String getItemImageURL() {
        return ItemImageURL;
    }

    /**
     * @param ItemImageURL the ItemImageURL to set
     */
    public void setItemImageURL(String ItemImageURL) {
        this.ItemImageURL = ItemImageURL;
    }

    /**
     * @return the ItemRating
     */
    public int getItemRating() {
        return ItemRating;
    }

    /**
     * @param ItemRating the ItemRating to set
     */
    public void setItemRating(int ItemRating) {
        this.ItemRating = ItemRating;
    }

    /**
     * @return the FullDescription
     */
    public String getFullDescription() {
        return FullDescription;
    }

    /**
     * @param FullDescription the FullDescription to set
     */
    public void setFullDescription(String FullDescription) {
        this.FullDescription = FullDescription;
    }

    /**
     * @return the AvailableQuantity
     */
    public int getAvailableQuantity() {
        return AvailableQuantity;
    }

    /**
     * @param AvailableQuantity the AvailableQuantity to set
     */
    public void setAvailableQuantity(int AvailableQuantity) {
        this.AvailableQuantity = AvailableQuantity;
    }
}

src/java/model/Item.java
package model;


import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nam
 */
public class Item {
    private int ItemID;
    private int UserID;
    private String ItemName;
    private double Price;
    private int AvailableQuantity;
    private String FullDescription;
    private String MagicDescription;
    private String BareNecessities;
    private String DeliveryDetail;
    private String ItemImageURL;
    private Date CreatedDate;
    private String State;
    private String ItemType;
    private String Color;
    private float Width;
    private float Height;
    private String Material;

    /**
     * @return the ItemID
     */
    public int getItemID() {
        return ItemID;
    }

    /**
     * @param ItemID the ItemID to set
     */
    public void setItemID(int ItemID) {
        this.ItemID = ItemID;
    }

    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the ItemName
     */
    public String getItemName() {
        return ItemName;
    }

    /**
     * @param ItemName the ItemName to set
     */
    public void setItemName(String ItemName) {
        this.ItemName = ItemName;
    }

    /**
     * @return the Price
     */
    public double getPrice() {
        return Price;
    }

    /**
     * @param Price the Price to set
     */
    public void setPrice(double Price) {
        this.Price = Price;
    }

    /**
     * @return the AvailableQuantity
     */
    public int getAvailableQuantity() {
        return AvailableQuantity;
    }

    /**
     * @param AvailableQuantity the AvailableQuantity to set
     */
    public void setAvailableQuantity(int AvailableQuantity) {
        this.AvailableQuantity = AvailableQuantity;
    }

    /**
     * @return the FullDescription
     */
    public String getFullDescription() {
        return FullDescription;
    }

    /**
     * @param FullDescription the FullDescription to set
     */
    public void setFullDescription(String FullDescription) {
        this.FullDescription = FullDescription;
    }

    /**
     * @return the MagicDescription
     */
    public String getMagicDescription() {
        return MagicDescription;
    }

    /**
     * @param MagicDescription the MagicDescription to set
     */
    public void setMagicDescription(String MagicDescription) {
        this.MagicDescription = MagicDescription;
    }

    /**
     * @return the BareNecessities
     */
    public String getBareNecessities() {
        return BareNecessities;
    }

    /**
     * @param BareNecessities the BareNecessities to set
     */
    public void setBareNecessities(String BareNecessities) {
        this.BareNecessities = BareNecessities;
    }

    /**
     * @return the DeliveryDetail
     */
    public String getDeliveryDetail() {
        return DeliveryDetail;
    }

    /**
     * @param DeliveryDetail the DeliveryDetail to set
     */
    public void setDeliveryDetail(String DeliveryDetail) {
        this.DeliveryDetail = DeliveryDetail;
    }

    /**
     * @return the ItemImageURL
     */
    public String getItemImageURL() {
        return ItemImageURL;
    }

    /**
     * @param ItemImageURL the ItemImageURL to set
     */
    public void setItemImageURL(String ItemImageURL) {
        this.ItemImageURL = ItemImageURL;
    }

    /**
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return CreatedDate;
    }

    /**
     * @param CreatedDate the CreatedDate to set
     */
    public void setCreatedDate(Date CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

    /**
     * @return the State
     */
    public String getState() {
        return State;
    }

    /**
     * @param State the State to set
     */
    public void setState(String State) {
        this.State = State;
    }

    /**
     * @return the ItemType
     */
    public String getItemType() {
        return ItemType;
    }

    /**
     * @param ItemType the ItemType to set
     */
    public void setItemType(String ItemType) {
        this.ItemType = ItemType;
    }

    /**
     * @return the Color
     */
    public String getColor() {
        return Color;
    }

    /**
     * @param Color the Color to set
     */
    public void setColor(String Color) {
        this.Color = Color;
    }

    /**
     * @return the Width
     */
    public float getWidth() {
        return Width;
    }

    /**
     * @param Width the Width to set
     */
    public void setWidth(float Width) {
        this.Width = Width;
    }

    /**
     * @return the Height
     */
    public float getHeight() {
        return Height;
    }

    /**
     * @param Height the Height to set
     */
    public void setHeight(float Height) {
        this.Height = Height;
    }

    /**
     * @return the Material
     */
    public String getMaterial() {
        return Material;
    }

    /**
     * @param Material the Material to set
     */
    public void setMaterial(String Material) {
        this.Material = Material;
    }
}

src/java/model/Order.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.Date;

/**
 *
 * @author Nam
 */
public class Order {
    private int OrderID;
    private int UserID;
    private String Username;
    private int TimeSlotID;
    private String FromTime;
    private String ToTime;
    private String OrderStatus;
    private Date OrderDate;
    private Date DeliveryDate;
    private String BankName;
    private String AccountNumber;
    private String AccountHolder;
    private String ShippingAddress;
    private float TotalAmount;
    /**
     * @return the OrderID
     */
    public int getOrderID() {
        return OrderID;
    }

    /**
     * @param OrderID the OrderID to set
     */
    public void setOrderID(int OrderID) {
        this.OrderID = OrderID;
    }

    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the TimeSlotID
     */
    public int getTimeSlotID() {
        return TimeSlotID;
    }

    /**
     * @param TimeSlotID the TimeSlotID to set
     */
    public void setTimeSlotID(int TimeSlotID) {
        this.TimeSlotID = TimeSlotID;
    }

    /**
     * @return the OrderStatus
     */
    public String getOrderStatus() {
        return OrderStatus;
    }

    /**
     * @param OrderStatus the OrderStatus to set
     */
    public void setOrderStatus(String OrderStatus) {
        this.OrderStatus = OrderStatus;
    }

    /**
     * @return the OrderDate
     */
    public Date getOrderDate() {
        return OrderDate;
    }

    /**
     * @param OrderDate the OrderDate to set
     */
    public void setOrderDate(Date OrderDate) {
        this.OrderDate = OrderDate;
    }

    /**
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return DeliveryDate;
    }

    /**
     * @param DeliveryDate the DeliveryDate to set
     */
    public void setDeliveryDate(Date DeliveryDate) {
        this.DeliveryDate = DeliveryDate;
    }

    /**
     * @return the BankName
     */
    public String getBankName() {
        return BankName;
    }

    /**
     * @param BankName the BankName to set
     */
    public void setBankName(String BankName) {
        this.BankName = BankName;
    }

    /**
     * @return the AccountNumber
     */
    public String getAccountNumber() {
        return AccountNumber;
    }

    /**
     * @param AccountNumber the AccountNumber to set
     */
    public void setAccountNumber(String AccountNumber) {
        this.AccountNumber = AccountNumber;
    }

    /**
     * @return the AccountHolder
     */
    public String getAccountHolder() {
        return AccountHolder;
    }

    /**
     * @param AccountHolder the AccountHolder to set
     */
    public void setAccountHolder(String AccountHolder) {
        this.AccountHolder = AccountHolder;
    }

    /**
     * @return the Username
     */
    public String getUsername() {
        return Username;
    }

    /**
     * @param Username the Username to set
     */
    public void setUsername(String Username) {
        this.Username = Username;
    }

    /**
     * @return the FromTime
     */
    public String getFromTime() {
        return FromTime;
    }

    /**
     * @param FromTime the FromTime to set
     */
    public void setFromTime(String FromTime) {
        this.FromTime = FromTime;
    }

    /**
     * @return the ToTime
     */
    public String getToTime() {
        return ToTime;
    }

    /**
     * @param ToTime the ToTime to set
     */
    public void setToTime(String ToTime) {
        this.ToTime = ToTime;
    }

	/**
	 * @return the ShippingAddress
	 */
	public String getShippingAddress() {
		return ShippingAddress;
	}

	/**
	 * @param ShippingAddress the ShippingAddress to set
	 */
	public void setShippingAddress(String ShippingAddress) {
		this.ShippingAddress = ShippingAddress;
	}

	/**
	 * @return the TotalAmount
	 */
	public float getTotalAmount() {
		return TotalAmount;
	}

	/**
	 * @param TotalAmount the TotalAmount to set
	 */
	public void setTotalAmount(float TotalAmount) {
		this.TotalAmount = TotalAmount;
	}
}

src/java/model/User.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author Nam
 */
public class User {
    private int UserID;
    private String LoginEmail;
    private String LastName;
    private String FirstName;
    private String Gender;
    private int ContactNumber;
    private String Password;
    private String DefaultBankName;
    private String DefaultAccountNumber;
    private String DefaultAccountHolder;
    private String ShippingAddress1;
    private String ShippingAddress2;
    private int IsAdmin;
    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the LoginEmail
     */
    public String getLoginEmail() {
        return LoginEmail;
    }

    /**
     * @param LoginEmail the LoginEmail to set
     */
    public void setLoginEmail(String LoginEmail) {
        this.LoginEmail = LoginEmail;
    }

    /**
     * @return the LastName
     */
    public String getLastName() {
        return LastName;
    }

    /**
     * @param LastName the LastName to set
     */
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    /**
     * @return the FirstName
     */
    public String getFirstName() {
        return FirstName;
    }

    /**
     * @param FirstName the FirstName to set
     */
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    /**
     * @return the Gender
     */
    public String getGender() {
        return Gender;
    }

    /**
     * @param Gender the Gender to set
     */
    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    /**
     * @return the ContactNumber
     */
    public int getContactNumber() {
        return ContactNumber;
    }

    /**
     * @param ContactNumber the ContactNumber to set
     */
    public void setContactNumber(int ContactNumber) {
        this.ContactNumber = ContactNumber;
    }

    /**
     * @return the Password
     */
    public String getPassword() {
        return Password;
    }

    /**
     * @param Password the Password to set
     */
    public void setPassword(String Password) {
        this.Password = Password;
    }

    /**
     * @return the DefaultBankName
     */
    public String getDefaultBankName() {
        return DefaultBankName;
    }

    /**
     * @param DefaultBankName the DefaultBankName to set
     */
    public void setDefaultBankName(String DefaultBankName) {
        this.DefaultBankName = DefaultBankName;
    }

    /**
     * @return the DefaultAccountNumber
     */
    public String getDefaultAccountNumber() {
        return DefaultAccountNumber;
    }

    /**
     * @param DefaultAccountNumber the DefaultAccountNumber to set
     */
    public void setDefaultAccountNumber(String DefaultAccountNumber) {
        this.DefaultAccountNumber = DefaultAccountNumber;
    }

    /**
     * @return the DefaultAccountHolder
     */
    public String getDefaultAccountHolder() {
        return DefaultAccountHolder;
    }

    /**
     * @param DefaultAccountHolder the DefaultAccountHolder to set
     */
    public void setDefaultAccountHolder(String DefaultAccountHolder) {
        this.DefaultAccountHolder = DefaultAccountHolder;
    }

    /**
     * @return the IsAdmin
     */
    public int getIsAdmin() {
        return IsAdmin;
    }

    /**
     * @param IsAdmin the IsAdmin to set
     */
    public void setIsAdmin(int IsAdmin) {
        this.IsAdmin = IsAdmin;
    }

    /**
     * @return the ShippingAddress1
     */
    public String getShippingAddress1() {
        return ShippingAddress1;
    }

    /**
     * @param ShippingAddress1 the ShippingAddress1 to set
     */
    public void setShippingAddress1(String ShippingAddress1) {
        this.ShippingAddress1 = ShippingAddress1;
    }

    /**
     * @return the ShippingAddress2
     */
    public String getShippingAddress2() {
        return ShippingAddress2;
    }

    /**
     * @param ShippingAddress2 the ShippingAddress2 to set
     */
    public void setShippingAddress2(String ShippingAddress2) {
        this.ShippingAddress2 = ShippingAddress2;
    }
}

web/admin/editCategory.jsp
<jsp:include page="../inc/header.jsp"/>
<div id="page-wrapper">
	<%--<jsp:useBean id="category" type="model.Category" scope="request"/>--%>
	<section class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h3 class="page-header ">
					Edit Category
				</h3>
				<ol class="breadcrumb">

					<li class="active">
						<i class="fa fa-book"></i> <a href="CategoryController?action=list">Product Category</a>
					</li>
					<li class="active">
						<i class="fa fa-pencil-square-o"></i> Edit Category
					</li>
				</ol>
			</div>
		</div>
		<form method="POST" action='CategoryController' class="form-horizontal">
			<div class="form-group">
				<label class="control-label col-lg-4 insert">Category Name : </label>
				<div class="col-lg-5">
					<input name="categoryName" type="text" class="form-control" value="${category.categoryName}">
				</div>
			</div>
			<input name="categoryID" type="hidden" value="${category.categoryID}">
			<div class="form-group">
				<div class="col-lg-offset-4 col-lg-6">
					<a class="btn btn-default col-lg-3 save-btn" href="CategoryController?action=list" role="button">Cancel</a>
					<input type="submit" value="Save" class="btn btn-primary col-lg-3 save-btn"/>
				</div>
			</div>
		</form>
	</section>
</div>
</body>
</html>

web/admin/editOrder.jsp
<jsp:include page="../inc/header.jsp"/>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<div id="page-wrapper">
	<section class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h3 class="page-header ">
					Edit Order
				</h3>
				<ol class="breadcrumb">

					<li class="active">
						<i class="fa fa-newspaper-o"></i> <a href="OrderController?action=list">Order</a>
					</li>
					<li class="active">
						<i class="fa fa-pencil-square-o"></i> Edit Order
					</li>
				</ol>
			</div>
		</div>

		<form method="POST" action='OrderController' class="form-horizontal">

				<div class="form-group">
					<label class="control-label col-lg-4 insert">User : </label>
					<div class="col-lg-5">
						<select name="userID" class="form-control">
							<c:forEach items="${users}" var="user">
								<option value="<c:out value="${user.userID}"/>"
									   <c:if test="${user.userID==order.userID}">selected</c:if>
										   >
									   <c:out value="${user.firstName} ${user.lastName} [ID: ${user.userID}]"/>
								</option>
							</c:forEach>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4 insert">Order Status : </label>
					<div class="col-lg-5">
						<select name="orderStatus" class="form-control">
							<option value="Pending" <c:if test="${order.orderStatus == 'Pending'}">selected</c:if>>Pending</option>
							<option value="Completed" <c:if test="${order.orderStatus == 'Completed'}">selected</c:if>>Completed</option>
							<option value="Cancel" <c:if test="${order.orderStatus=='Cancel'}">selected</c:if>>Cancel</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4 insert">Delivery Date : </label>
					<div class="col-lg-5">
						<input type="text" name="deliveryDate" class="form-control" value="<c:out value="${order.deliveryDate}"/>">
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4 insert">Time Slot : </label>
					<div class="col-lg-5">
						<select name="timeSlotID" class="form-control">
							<c:forEach items="${timeSlots}" var="timeSlot">
								<option value="<c:out value="${timeSlot.timeSlotID}"/>"
									   <c:if test="${timeSlot.timeSlotID==order.timeSlotID}">selected</c:if>
										   >
									   <c:out value="${timeSlot.fromTime} - ${timeSlot.toTime}"/>
								</option>
							</c:forEach>
						</select>
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-lg-4 insert">Bank Name : </label>
					<div class="col-lg-5">
						<select name="bankName" class="form-control">
							<option value="Bank of China (Hong Kong)" <c:if test="${order.bankName == 'Bank of China (Hong Kong)'}">selected</c:if>>Bank of China (Hong Kong)</option>
							<option value="Bank of East Asia"  <c:if test="${order.bankName == 'Bank of East Asia'}">selected</c:if>>Bank of East Asia</option>
							<option value="Hang Seng Bank"  <c:if test="${order.bankName == 'Hang Seng Bank'}">selected</c:if>>Hang Seng Bank</option>
							<option value="Hongkong and Shanghai Banking Corporation"  <c:if test="${order.bankName == 'Hongkong and Shanghai Banking Corporation'}">selected</c:if>>Hongkong and Shanghai Banking Corporation</option>
							<option value="Industrial and Commercial Bank of China (Asia)"  <c:if test="${order.bankName == 'Industrial and Commercial Bank of China (Asia)'}">selected</c:if>>Industrial and Commercial Bank of China (Asia)</option>
							<option value="Standard Chartered Bank (Hong Kong)"  <c:if test="${order.bankName == 'Standard Chartered Bank (Hong Kong)'}">selected</c:if>>Standard Chartered Bank (Hong Kong)</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-lg-4 insert">Account Number : </label>
						<div class="col-lg-5">
							<input name="accountNumber" type="number" class="form-control" value="${order.accountNumber}">
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4 insert">Account Holder : </label>
					<div class="col-lg-5">
						<input name="accountHolder" type="text" class="form-control" value="${order.accountHolder}">
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4 insert">Shipping Address : </label>
					<div class="col-lg-5">
						<input name="shippingAddress" type="text" class="form-control" value="${order.shippingAddress}">
					</div>
				</div>				

			<input type="hidden" name="orderID" value="<c:out value="${order.orderID}"/>"
			<div class="form-group">
				<div class="col-lg-offset-4 col-lg-6">
					<a class="btn btn-default col-lg-3 save-btn" href="OrderController?action=list" role="button">Cancel</a>
					<input type="submit" value="Save" class="btn btn-primary col-lg-3 save-btn"/>
		
				</div>
			</div>
		</form>
	</section>
</div>
</body>
</html>

web/admin/insertCategory.jsp
<jsp:include page="../inc/header.jsp"/>
<div id="page-wrapper">
	<section class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h3 class="page-header ">
					Add Category
				</h3>
				<ol class="breadcrumb">
				
					<li class="active">
						<i class="fa fa-book"></i> <a href="CategoryController?action=list">Product Category</a>
					</li>
					<li class="active">
						<i class="fa fa-check-square-o"></i> Add Category
					</li>
				</ol>
			</div>
		</div>
		<form method="POST" action='CategoryController' class="form-horizontal">
			<div class="form-group ">
				<label class="control-label col-lg-4 insert">Category Name : </label>
				<div class="col-lg-5">
					<input name="categoryName" type="text" class="form-control">
				</div>
			</div>
			<div class="form-group">
				<div class="col-lg-offset-4 col-lg-5">
					<a class="btn btn-default col-lg-3 save-btn" href="CategoryController?action=list" role="button">Cancel</a>
					<input type="submit" value="Add" class="btn btn-primary col-lg-3 save-btn"/>
				</div>
			</div>
		</form>
	</section>
</div>
</body>
</html>

web/admin/insertOrder.jsp
<jsp:include page="../inc/header.jsp"/>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
    <section class="container-fluid">
        <h2>Add Time Slot</h2>
        <form method="POST" action='OrderController' class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-lg-4">User : </label>
                <div class="col-lg-5">
                    <select name="userID" class="form-control">
                        <c:forEach items="${users}" var="user">
                            <option value="<c:out value="${user.userID}"/>"><c:out value="${user.firstName} ${user.lastName} [ID: ${user.userID}]"/></option>
                        </c:forEach>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-4">Delivery Date : </label>
                <div class="col-lg-5">
                    <input type="text" name="deliveryDate" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-4">Time Slot : </label>
                <div class="col-lg-5">
                    <select name="timeSlotID" class="form-control">
                        <c:forEach items="${timeSlots}" var="timeSlot">
                            <option value="<c:out value="${timeSlot.timeSlotID}"/>"><c:out value="${timeSlot.fromTime} - ${timeSlot.toTime}"/></option>
                        </c:forEach>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-4">Order Status : </label>
                <div class="col-lg-5">
                    <select name="orderStatus" class="form-control">
                        <option value="Pending">Pending</option>
                        <option value="Completed">Completed</option>
                        <option value="Cancel">Cancel</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-4">Bank Name : </label>
                <div class="col-lg-5">
                    <input type="text" name="bankName" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-4">Account Number : </label>
                <div class="col-lg-5">
                    <input type="number" name="accountNumber" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-4">Account Holder : </label>
                <div class="col-lg-5">
                    <input type="text" name="accountHolder" class="form-control">
                </div>
            </div>
           <div class="form-group">
                <label class="control-label col-lg-4">Shipping Address : </label>
                <div class="col-lg-5">
                    <input type="text" name="shippingAddress" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-4 col-lg-5">
                    <input type="submit" value="Submit" class="btn btn-primary"/>
                </div>
            </div>
        </form>
    </section>
</body>
</html>

web/admin/listReview.jsp
<jsp:include page="../inc/header.jsp"/>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<h3 class="page-header">
					Product Comment
				</h3>
				<ol class="breadcrumb">
				
					<li class="active">
						<i class="fa fa-comments"></i> Product Comment
					</li>
				</ol>
			</div>
		</div>	

		<p>
			<a class="pull-right btn btn-warning fa fa-comments">     Reply Comment</a>
			<a  class="pull-right btn btn-info fa fa-pencil-square-o">     Edit</a>
			<a class="pull-right btn btn-success fa fa-search-plus">     View</a>

		</p>

		<div class= table-responsive">
			<table class="table table-striped table-hover">
				<thead class="table-head">
					<tr>
						<th>ID</th>
						<th>User</th>
						<th>Review Product</th>
						<th>Product Rating</th>
						<th>Title</th>
						<th>Created Date</th>
						<th colspan=3>Action</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach items="${reviews}" var="review">
						<tr>
							<td>${review.reviewID}</td>
							<td>${review.firstName} ${review.lastName} [ID: ${review.userID}]</td>
							<td>${review.itemName} [ID: ${review.itemID}]</td>
							<td>${review.itemRating}</td>
							<td>${review.title}</td>
							<td>${review.createdDate}</td>
							<td>

								<a href="ReviewController?action=view&reviewID=${review.reviewID}" class="btn btn-success fa fa-search-plus"></a>
								<a href="ReviewController?action=edit&reviewID=${review.reviewID}" class="btn btn-info fa fa-pencil-square-o"></a>
								<c:if test="${review.replyID == 0}">
									<a href="ReviewController?action=insert&reviewID=${review.reviewID}" class="btn btn-warning fa fa-comments"></a>	
								</c:if>
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</div>
	</div>
</div>
</body>
</html>