src/java/model/Cart.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author Nam
 */
public class Cart {
    private int CartID;
    private int UserID;
    private int ItemID;
    private int Quantity;
    private int AvailableQuantity;
    private float Price;
    private String ItemImageURL;
    private int ItemRating;
    private String FullDescription;

    /**
     * @return the CartID
     */
    public int getCartID() {
        return CartID;
    }

    /**
     * @param CartID the CartID to set
     */
    public void setCartID(int CartID) {
        this.CartID = CartID;
    }

    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the ItemID
     */
    public int getItemID() {
        return ItemID;
    }

    /**
     * @param ItemID the ItemID to set
     */
    public void setItemID(int ItemID) {
        this.ItemID = ItemID;
    }

    /**
     * @return the Quantity
     */
    public int getQuantity() {
        return Quantity;
    }

    /**
     * @param Quantity the Quantity to set
     */
    public void setQuantity(int Quantity) {
        this.Quantity = Quantity;
    }

    /**
     * @return the Price
     */
    public float getPrice() {
        return Price;
    }

    /**
     * @param Price the Price to set
     */
    public void setPrice(float Price) {
        this.Price = Price;
    }

    /**
     * @return the ItemImageURL
     */
    public String getItemImageURL() {
        return ItemImageURL;
    }

    /**
     * @param ItemImageURL the ItemImageURL to set
     */
    public void setItemImageURL(String ItemImageURL) {
        this.ItemImageURL = ItemImageURL;
    }

    /**
     * @return the ItemRating
     */
    public int getItemRating() {
        return ItemRating;
    }

    /**
     * @param ItemRating the ItemRating to set
     */
    public void setItemRating(int ItemRating) {
        this.ItemRating = ItemRating;
    }

    /**
     * @return the FullDescription
     */
    public String getFullDescription() {
        return FullDescription;
    }

    /**
     * @param FullDescription the FullDescription to set
     */
    public void setFullDescription(String FullDescription) {
        this.FullDescription = FullDescription;
    }

    /**
     * @return the AvailableQuantity
     */
    public int getAvailableQuantity() {
        return AvailableQuantity;
    }

    /**
     * @param AvailableQuantity the AvailableQuantity to set
     */
    public void setAvailableQuantity(int AvailableQuantity) {
        this.AvailableQuantity = AvailableQuantity;
    }
}

src/java/model/Item.java
package model;


import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nam
 */
public class Item {
    private int ItemID;
    private int UserID;
    private String ItemName;
    private double Price;
    private int AvailableQuantity;
    private String FullDescription;
    private String MagicDescription;
    private String BareNecessities;
    private String DeliveryDetail;
    private String ItemImageURL;
    private Date CreatedDate;
    private String State;
    private String ItemType;
    private String Color;
    private float Width;
    private float Height;
    private String Material;

    /**
     * @return the ItemID
     */
    public int getItemID() {
        return ItemID;
    }

    /**
     * @param ItemID the ItemID to set
     */
    public void setItemID(int ItemID) {
        this.ItemID = ItemID;
    }

    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the ItemName
     */
    public String getItemName() {
        return ItemName;
    }

    /**
     * @param ItemName the ItemName to set
     */
    public void setItemName(String ItemName) {
        this.ItemName = ItemName;
    }

    /**
     * @return the Price
     */
    public double getPrice() {
        return Price;
    }

    /**
     * @param Price the Price to set
     */
    public void setPrice(double Price) {
        this.Price = Price;
    }

    /**
     * @return the AvailableQuantity
     */
    public int getAvailableQuantity() {
        return AvailableQuantity;
    }

    /**
     * @param AvailableQuantity the AvailableQuantity to set
     */
    public void setAvailableQuantity(int AvailableQuantity) {
        this.AvailableQuantity = AvailableQuantity;
    }

    /**
     * @return the FullDescription
     */
    public String getFullDescription() {
        return FullDescription;
    }

    /**
     * @param FullDescription the FullDescription to set
     */
    public void setFullDescription(String FullDescription) {
        this.FullDescription = FullDescription;
    }

    /**
     * @return the MagicDescription
     */
    public String getMagicDescription() {
        return MagicDescription;
    }

    /**
     * @param MagicDescription the MagicDescription to set
     */
    public void setMagicDescription(String MagicDescription) {
        this.MagicDescription = MagicDescription;
    }

    /**
     * @return the BareNecessities
     */
    public String getBareNecessities() {
        return BareNecessities;
    }

    /**
     * @param BareNecessities the BareNecessities to set
     */
    public void setBareNecessities(String BareNecessities) {
        this.BareNecessities = BareNecessities;
    }

    /**
     * @return the DeliveryDetail
     */
    public String getDeliveryDetail() {
        return DeliveryDetail;
    }

    /**
     * @param DeliveryDetail the DeliveryDetail to set
     */
    public void setDeliveryDetail(String DeliveryDetail) {
        this.DeliveryDetail = DeliveryDetail;
    }

    /**
     * @return the ItemImageURL
     */
    public String getItemImageURL() {
        return ItemImageURL;
    }

    /**
     * @param ItemImageURL the ItemImageURL to set
     */
    public void setItemImageURL(String ItemImageURL) {
        this.ItemImageURL = ItemImageURL;
    }

    /**
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return CreatedDate;
    }

    /**
     * @param CreatedDate the CreatedDate to set
     */
    public void setCreatedDate(Date CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

    /**
     * @return the State
     */
    public String getState() {
        return State;
    }

    /**
     * @param State the State to set
     */
    public void setState(String State) {
        this.State = State;
    }

    /**
     * @return the ItemType
     */
    public String getItemType() {
        return ItemType;
    }

    /**
     * @param ItemType the ItemType to set
     */
    public void setItemType(String ItemType) {
        this.ItemType = ItemType;
    }

    /**
     * @return the Color
     */
    public String getColor() {
        return Color;
    }

    /**
     * @param Color the Color to set
     */
    public void setColor(String Color) {
        this.Color = Color;
    }

    /**
     * @return the Width
     */
    public float getWidth() {
        return Width;
    }

    /**
     * @param Width the Width to set
     */
    public void setWidth(float Width) {
        this.Width = Width;
    }

    /**
     * @return the Height
     */
    public float getHeight() {
        return Height;
    }

    /**
     * @param Height the Height to set
     */
    public void setHeight(float Height) {
        this.Height = Height;
    }

    /**
     * @return the Material
     */
    public String getMaterial() {
        return Material;
    }

    /**
     * @param Material the Material to set
     */
    public void setMaterial(String Material) {
        this.Material = Material;
    }
}

src/java/model/Order.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.Date;

/**
 *
 * @author Nam
 */
public class Order {
    private int OrderID;
    private int UserID;
    private String Username;
    private int TimeSlotID;
    private String FromTime;
    private String ToTime;
    private String OrderStatus;
    private Date OrderDate;
    private Date DeliveryDate;
    private String BankName;
    private String AccountNumber;
    private String AccountHolder;
    private String ShippingAddress;
    private float TotalAmount;
    /**
     * @return the OrderID
     */
    public int getOrderID() {
        return OrderID;
    }

    /**
     * @param OrderID the OrderID to set
     */
    public void setOrderID(int OrderID) {
        this.OrderID = OrderID;
    }

    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the TimeSlotID
     */
    public int getTimeSlotID() {
        return TimeSlotID;
    }

    /**
     * @param TimeSlotID the TimeSlotID to set
     */
    public void setTimeSlotID(int TimeSlotID) {
        this.TimeSlotID = TimeSlotID;
    }

    /**
     * @return the OrderStatus
     */
    public String getOrderStatus() {
        return OrderStatus;
    }

    /**
     * @param OrderStatus the OrderStatus to set
     */
    public void setOrderStatus(String OrderStatus) {
        this.OrderStatus = OrderStatus;
    }

    /**
     * @return the OrderDate
     */
    public Date getOrderDate() {
        return OrderDate;
    }

    /**
     * @param OrderDate the OrderDate to set
     */
    public void setOrderDate(Date OrderDate) {
        this.OrderDate = OrderDate;
    }

    /**
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return DeliveryDate;
    }

    /**
     * @param DeliveryDate the DeliveryDate to set
     */
    public void setDeliveryDate(Date DeliveryDate) {
        this.DeliveryDate = DeliveryDate;
    }

    /**
     * @return the BankName
     */
    public String getBankName() {
        return BankName;
    }

    /**
     * @param BankName the BankName to set
     */
    public void setBankName(String BankName) {
        this.BankName = BankName;
    }

    /**
     * @return the AccountNumber
     */
    public String getAccountNumber() {
        return AccountNumber;
    }

    /**
     * @param AccountNumber the AccountNumber to set
     */
    public void setAccountNumber(String AccountNumber) {
        this.AccountNumber = AccountNumber;
    }

    /**
     * @return the AccountHolder
     */
    public String getAccountHolder() {
        return AccountHolder;
    }

    /**
     * @param AccountHolder the AccountHolder to set
     */
    public void setAccountHolder(String AccountHolder) {
        this.AccountHolder = AccountHolder;
    }

    /**
     * @return the Username
     */
    public String getUsername() {
        return Username;
    }

    /**
     * @param Username the Username to set
     */
    public void setUsername(String Username) {
        this.Username = Username;
    }

    /**
     * @return the FromTime
     */
    public String getFromTime() {
        return FromTime;
    }

    /**
     * @param FromTime the FromTime to set
     */
    public void setFromTime(String FromTime) {
        this.FromTime = FromTime;
    }

    /**
     * @return the ToTime
     */
    public String getToTime() {
        return ToTime;
    }

    /**
     * @param ToTime the ToTime to set
     */
    public void setToTime(String ToTime) {
        this.ToTime = ToTime;
    }

	/**
	 * @return the ShippingAddress
	 */
	public String getShippingAddress() {
		return ShippingAddress;
	}

	/**
	 * @param ShippingAddress the ShippingAddress to set
	 */
	public void setShippingAddress(String ShippingAddress) {
		this.ShippingAddress = ShippingAddress;
	}

	/**
	 * @return the TotalAmount
	 */
	public float getTotalAmount() {
		return TotalAmount;
	}

	/**
	 * @param TotalAmount the TotalAmount to set
	 */
	public void setTotalAmount(float TotalAmount) {
		this.TotalAmount = TotalAmount;
	}
}

src/java/model/User.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author Nam
 */
public class User {
    private int UserID;
    private String LoginEmail;
    private String LastName;
    private String FirstName;
    private String Gender;
    private int ContactNumber;
    private String Password;
    private String DefaultBankName;
    private String DefaultAccountNumber;
    private String DefaultAccountHolder;
    private String ShippingAddress1;
    private String ShippingAddress2;
    private int IsAdmin;
    /**
     * @return the UserID
     */
    public int getUserID() {
        return UserID;
    }

    /**
     * @param UserID the UserID to set
     */
    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    /**
     * @return the LoginEmail
     */
    public String getLoginEmail() {
        return LoginEmail;
    }

    /**
     * @param LoginEmail the LoginEmail to set
     */
    public void setLoginEmail(String LoginEmail) {
        this.LoginEmail = LoginEmail;
    }

    /**
     * @return the LastName
     */
    public String getLastName() {
        return LastName;
    }

    /**
     * @param LastName the LastName to set
     */
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    /**
     * @return the FirstName
     */
    public String getFirstName() {
        return FirstName;
    }

    /**
     * @param FirstName the FirstName to set
     */
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    /**
     * @return the Gender
     */
    public String getGender() {
        return Gender;
    }

    /**
     * @param Gender the Gender to set
     */
    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    /**
     * @return the ContactNumber
     */
    public int getContactNumber() {
        return ContactNumber;
    }

    /**
     * @param ContactNumber the ContactNumber to set
     */
    public void setContactNumber(int ContactNumber) {
        this.ContactNumber = ContactNumber;
    }

    /**
     * @return the Password
     */
    public String getPassword() {
        return Password;
    }

    /**
     * @param Password the Password to set
     */
    public void setPassword(String Password) {
        this.Password = Password;
    }

    /**
     * @return the DefaultBankName
     */
    public String getDefaultBankName() {
        return DefaultBankName;
    }

    /**
     * @param DefaultBankName the DefaultBankName to set
     */
    public void setDefaultBankName(String DefaultBankName) {
        this.DefaultBankName = DefaultBankName;
    }

    /**
     * @return the DefaultAccountNumber
     */
    public String getDefaultAccountNumber() {
        return DefaultAccountNumber;
    }

    /**
     * @param DefaultAccountNumber the DefaultAccountNumber to set
     */
    public void setDefaultAccountNumber(String DefaultAccountNumber) {
        this.DefaultAccountNumber = DefaultAccountNumber;
    }

    /**
     * @return the DefaultAccountHolder
     */
    public String getDefaultAccountHolder() {
        return DefaultAccountHolder;
    }

    /**
     * @param DefaultAccountHolder the DefaultAccountHolder to set
     */
    public void setDefaultAccountHolder(String DefaultAccountHolder) {
        this.DefaultAccountHolder = DefaultAccountHolder;
    }

    /**
     * @return the IsAdmin
     */
    public int getIsAdmin() {
        return IsAdmin;
    }

    /**
     * @param IsAdmin the IsAdmin to set
     */
    public void setIsAdmin(int IsAdmin) {
        this.IsAdmin = IsAdmin;
    }

    /**
     * @return the ShippingAddress1
     */
    public String getShippingAddress1() {
        return ShippingAddress1;
    }

    /**
     * @param ShippingAddress1 the ShippingAddress1 to set
     */
    public void setShippingAddress1(String ShippingAddress1) {
        this.ShippingAddress1 = ShippingAddress1;
    }

    /**
     * @return the ShippingAddress2
     */
    public String getShippingAddress2() {
        return ShippingAddress2;
    }

    /**
     * @param ShippingAddress2 the ShippingAddress2 to set
     */
    public void setShippingAddress2(String ShippingAddress2) {
        this.ShippingAddress2 = ShippingAddress2;
    }
}

web/cart.jsp
<jsp:include page="inc/head.jsp"/>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>  
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!--Main Content Start-->
<div class="cp-page-content inner-page-content woocommerce" style="padding-top: 0px">
    <div class="container">
        <p class="navigation">
            <a href="LandingController">Home</a>
            > Shopping Cart
        </p>
        <h2 class="new-sec-title">Shopping Cart</h2>
        <div class="row">
            <div class="col-md-12">
                <div class="cart-table">
                    <div>
                        <ul>
                            <!--TABLE CAPS START-->
                            <li class="table-caps">
                                <div class="product">product</div>
                                <div class="detail">detail</div>
                                <div class="price">price</div>
                                <div class="quantity">Quantity</div>
                                <div class="total">Total</div>
                                <div class="del">Del</div>
                            </li>
                            <!--TABLE CAPS END--> 
                            <c:forEach items="${items}" var="item">
                                <!--CART LIST START-->
                                <li>
                                    <div class="product"><a href="product?pid=${item.itemID}"><img alt="" src="data/${item.itemImageURL}"></a></div>
                                    <div class="detail">
                                        <c:set var="description" value="${item.fullDescription}"/>
                                        <p><c:out value="${fn:substring(description, 0, 30)}..."/></p>
                                        <!--<div class="rating"> <i class="fa fa-star"></i><i class="fa fa-star"></i> </div>-->
                                        <p>Product code: ${item.itemID}</p>
                                    </div>
                                    <div class="price">
                                        <p>$ ${item.price}</p>
                                    </div>

                                    <div class="quantity">
                                        <form method='POST' action="cart">
                                            <input type="hidden" value="${item.cartID}" name="cartID">
                                            <input type="hidden" value="edit" name="action">
                                            <input type="hidden" name="itemID" value="${item.itemID}">
                                            <input type='number' name='quantity' value='${item.quantity}' class='qty' min="1" max="${item.availableQuantity}"/>
                                            <input type="submit" value="update" class="btn btn-info">
                                        </form>
                                    </div>

                                    <div class="total">
                                        <p><fmt:formatNumber value="${item.quantity * item.price}" type="number" maxFractionDigits="1"></fmt:formatNumber></p>
                                        </div>
                                        <div class="del">
                                            <a class="fa fa-trash" href="cart?action=delete&cartID=${item.cartID}"></a>
                                    </div>

                                </li>
                                <!--CART LIST END--> 
                            </c:forEach>
                        </ul>
                        <!--					<div class="update-cart">
                                                                        
                                                                </div>-->
                    </div>
                    <div>
                        <form method="POST" action="cart?action=checkout" class="registration-form horizontal-form" style="width: 70%; margin-top: 40px">
                            <fieldset class="account-profile-border registration-border">
                                <legend class="recycle-border">Delivery Detail</legend>

                                <div class="form-group row">
                                    <label class="form-control-label col-sm-4" >Choose a Shipping Address</label>
                                    <!--PROBLEM HERE check out use radio button-->
<!--                                    <div class="form-control-label col-sm-8" >-->
                                        <select name="shippingAddress" class="form-control" style="font-weight: normal; width: 65%">
                                            <option value="${user.shippingAddress1}">${user.shippingAddress1}</option>
                                            <option value="${user.shippingAddress2}">${user.shippingAddress2}</option>
                                        </select>
                                    <!--</div>-->
                                </div>

                                <div class="form-group row">
                                    <label class="form-control-label col-sm-4" >Delivery Schedule Date</label>
                                    <input class="form-control col-sm-8 "  type="text" name="deliveryDate" placeholder="delivery date format:  yyyy-mm-dd" style="font-weight: normal; width: 65%" required>
                                </div>

                                <div class="form-group row">
                                    <label class="form-control-label col-sm-4" >Delivery Schedule Timeslot</label>
                                    <select name="timeSlot"  class="form-control col-sm-8 "style="font-weight: normal; width: 65%">
                                        <c:forEach items="${timeSlots}" var="timeSlot">
                                            <option value="${timeSlot.timeSlotID}">${timeSlot.fromTime} - ${timeSlot.toTime}</option>
                                        </c:forEach>
                                    </select>
                                </div>
                                <input type="submit" class="pull-right btn btn-primary" value="Check Out">

                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Main Content End--> 
<jsp:include page="inc/foot.jsp"/>

web/wishlist.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="inc/head.jsp"/>  
<jsp:useBean id="user" type="model.User" scope="request"/>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>  
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<div class="cp-page-content background">
	<div class="container">
		<p class="navigation">
			<a href="LandingController">Home</a>
			> My Account
		</p>
		<h2 class="new-sec-title">Wishlist</h2>
		<div class="category-form" >

			<div class="col-sm-12">
<div class="cart-table">
                    <div>
                        <ul>
                            <!--TABLE CAPS START-->
                            <li class="table-caps">
                                <div class="product">product</div>
                                <div class="detail">detail</div>
                                <div class="price">price</div>
                                <div class="del">Del</div>
                            </li>
                            <!--TABLE CAPS END--> 
                            <c:forEach items="${items}" var="item">
                                <!--CART LIST START-->
                                <li>
                                    <div class="product"><a href="product?pid=${item.itemID}"><img alt="" src="data/${item.itemImageURL}"></a></div>
                                    <div class="detail">
                                        <c:set var="description" value="${item.fullDescription}"/>
                                        <p><c:out value="${fn:substring(description, 0, 30)}..."/></p>
                                        <!--<div class="rating"> <i class="fa fa-star"></i><i class="fa fa-star"></i> </div>-->
                                        <p>Product code: ${item.itemID}</p>
                                    </div>
                                    <div class="price">
                                        <p>$ ${item.price}</p>
                                    </div>

                                    <div class="quantity">
                                        <form method='POST' action="cart">
                                            <input type="hidden" value="${item.cartID}" name="cartID">
                                            <input type="hidden" value="edit" name="action">
                                            <input type="hidden" name="itemID" value="${item.itemID}">
                                            <input type='number' name='quantity' value='${item.quantity}' class='qty' min="1" max="${item.availableQuantity}"/>
                                            <input type="submit" value="update" class="btn btn-info">
                                        </form>
                                    </div>

                                  

                                </li>
                                <!--CART LIST END--> 
                            </c:forEach>
                        </ul>
                        <!--					<div class="update-cart">
                                                                        
                                                                </div>-->
                    </div>
                    <div>
                        <form method="POST" action="cart?action=checkout" class="registration-form horizontal-form" style="width: 70%; margin-top: 40px">
                            <fieldset class="account-profile-border registration-border">
                                <legend class="recycle-border">Delivery Detail</legend>

                                <div class="form-group row">
                                    <label class="form-control-label col-sm-4" >Choose a Shipping Address</label>
                                    <!--PROBLEM HERE check out use radio button-->
<!--                                    <div class="form-control-label col-sm-8" >-->
                                        <select name="shippingAddress" class="form-control" style="font-weight: normal; width: 65%">
                                            <option value="${user.shippingAddress1}">${user.shippingAddress1}</option>
                                            <option value="${user.shippingAddress2}">${user.shippingAddress2}</option>
                                        </select>
                                    <!--</div>-->
                                </div>

                                <div class="form-group row">
                                    <label class="form-control-label col-sm-4" >Delivery Schedule Date</label>
                                    <input class="form-control col-sm-8 "  type="text" name="deliveryDate" placeholder="delivery date format:  yyyy-mm-dd" style="font-weight: normal; width: 65%" required>
                                </div>

                                <div class="form-group row">
                                    <label class="form-control-label col-sm-4" >Delivery Schedule Timeslot</label>
                                    <select name="timeSlot"  class="form-control col-sm-8 "style="font-weight: normal; width: 65%">
                                        <c:forEach items="${timeSlots}" var="timeSlot">
                                            <option value="${timeSlot.timeSlotID}">${timeSlot.fromTime} - ${timeSlot.toTime}</option>
                                        </c:forEach>
                                    </select>
                                </div>
                                <input type="submit" class="pull-right btn btn-primary" value="Check Out">

                            </fieldset>
                        </form>
                    </div>
                </div>
			</div>
		</div>  
	</div>        
</div>
</div>
</div>
<!--Main Content End--> 
<jsp:include page="inc/foot.jsp"/>  